// <auto-generated />
using System;
using KL.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KL.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210609012457_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("KL.Domain.ClientScheduleService", b =>
                {
                    b.Property<int>("ClientsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScheduleServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientScheduleServiceClientsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientScheduleServiceScheduleServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientsId", "ScheduleServiceId");

                    b.HasIndex("ScheduleServiceId");

                    b.HasIndex("ClientScheduleServiceClientsId", "ClientScheduleServiceScheduleServiceId");

                    b.ToTable("ClientScheduleServices");
                });

            modelBuilder.Entity("KL.Domain.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlphaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodArea1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodArea2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhoneNumber2")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KL.Domain.Provinces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlphaCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("KL.Domain.ScheduleService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientsId");

                    b.ToTable("ScheduleService");
                });

            modelBuilder.Entity("KL.Domain.ClientScheduleService", b =>
                {
                    b.HasOne("KL.Domain.Clients", "Client")
                        .WithMany("ClientScheduleServices")
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KL.Domain.ScheduleService", "ScheduleService")
                        .WithMany()
                        .HasForeignKey("ScheduleServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KL.Domain.ClientScheduleService", null)
                        .WithMany("ClientScheduleServices")
                        .HasForeignKey("ClientScheduleServiceClientsId", "ClientScheduleServiceScheduleServiceId");

                    b.Navigation("Client");

                    b.Navigation("ScheduleService");
                });

            modelBuilder.Entity("KL.Domain.ScheduleService", b =>
                {
                    b.HasOne("KL.Domain.Clients", "Clients")
                        .WithMany("SchedulesServices")
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("KL.Domain.ClientScheduleService", b =>
                {
                    b.Navigation("ClientScheduleServices");
                });

            modelBuilder.Entity("KL.Domain.Clients", b =>
                {
                    b.Navigation("ClientScheduleServices");

                    b.Navigation("SchedulesServices");
                });
#pragma warning restore 612, 618
        }
    }
}
